name: Docker Image CI

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
      - '!deployement'
      - '!dev'

jobs:
  Build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run the Docker image
      run: docker run -v ${pwd}/dist:/usr/temp/build/dist -t deploypage:release